#Initialisation of paths
folderOutProdTmp <- 'output/tmp/production/'
folderOutConsTmp <- 'output/tmp/consumption/'
mainDir <- getwd()

#names
tmpFileNameProd <- '_CellProdYearly.csv'
tmpFileNameProvisoryProd <- '_CellProvisoryProdYearly.csv'
tmpFileNameCons <- '_CellConsYearly.csv'



#divers lists for provide parameters, dimensions, or definitions
listClusteringForRemoving <- c('S_PR1', 'S_PR2', 'S_PL', 'S_OEB_PL', 'S_OEB_ET', 'V_HS', 'V_MS', 'V_NS', 'V_INFO','V_BE', 'V_RL')
listClusteringCell <- list('H_0' = 'H0', 'H_1' = 'H0', 'H_2' = 'H0', 'H_3' = 'H0', 'H_4' = 'H0', 'H_5' = 'H0', 'H_6' = 'H0', 'H_UR' = 'H0', 'H_SR' = 'H0', 'H_RL' = 'H0', 
                           'G_RL' = 'G0', 'G0' = 'G0', 'G1' = 'G0', 'G2' = 'G0', 'G3' = 'G0', 'G4' = 'G0', 'G5' = 'G0', 'G6' = 'G0',
                           'L0' = 'L0', 'L1' = 'L0', 'L2' = 'L0', 'L' = 'L0')

listTarifsProd <- c('EEKEV', 'EEMKF', 'EN1', 'EU_PROF', 'EU_PROD', 'EU_TARIF', 'EU2')

listColNamesConProfile <- c('Week_S', 'Saturday_S', 'Sunday_S','Week_W', 'Saturday_W', 'Sunday_W', 'Week_TP', 'Saturday_TP', 'Sunday_TP')
listMonthPeriodAssign <- list('Summer' = c('May', 'June', 'July', 'August'), 'Winter' = c('January', 'February', 'March', 'November', 'December'), 'TransP' = c('April', 'September', 'October') )

listMonthsAssigned <- list('January' = 'W', 'February'= 'W', 'March'= 'W', 'April'= 'TP', 'May' = 'S', 'June' = 'S', 'July' = 'S', 'August' = 'S', 'September' = 'TP', 'October' = 'TP', 'November' = 'W', 'December' = 'W')

listMonths <- c('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December')

#Column names for the consumption and production files generated by functions "feedInPerCell" and "consumptionPerCell"
listColNamesInputFiles <- c('Anschlussobjekt', 'Produktion', 'MWh', 'Clustering')
#column names for reading the raw csv File - function "readCellFile"
listColNamesReadFiles <- c('Anschlussobjekt' = 'character', 'Tarif' = 'character', 'MWh' = 'integer', 'Clustering' = 'character')
#column names for the aggregate dataset file "aggrDataSetAll"
listColNamesAggrFile <- c('Anschlussobjekt' = 'character', 'MWh' = 'integer', 'Clustering' = 'character')
#provisory production list according the potential of the location
listProvisoryProd <- list('Good' = as.integer(5500), 'Medium' = as.integer(4000), 'Bad' = as.integer(3500))
#list of column names for the location file for CELLS
listColNamesLocCell <- c('Anschlussobjekt' = 'character', 'Trafo Nr' = 'integer', 'C Latitude' = 'double', 'C Longitude' = 'double')
#list of column names for the location file for TRAFO stations
listColNamesLocTrafo <- c('Trafo Nr' = 'integer', 'T Leistung' = 'integer', 'T Latitude' = 'double', 'T Longitude' = 'double')
#list of all production IDs
listCellProdIDs <- as.character(0)

#required list of packages
listReqPackages <- c('geosphere', 'sp', 'rgl', 'networkD3', 'caTools', 'igraph', 'gdistance', 'rgdal','RMySQL')


#load consumption profiles containing the distribution for private, business, and agriculture
consDistrH0 <- read.csv('input/Load profile add up H0.csv', sep = ';', header = TRUE, colClasses = c('Time' = 'character', rep('double',9)))
consDistrG0 <- read.csv('input/Load profile add up G0.csv', sep = ';', header = TRUE, colClasses = c('Time' = 'character', rep('double',9)))
consDistrL0 <- read.csv('input/Load profile add up L0.csv', sep = ';', header = TRUE, colClasses = c('Time' = 'character', rep('double',9)))

#load sun radiation profile
sunRadiationYearly <- read.csv('input/Average sun radiation DNI percentage - Spiez.csv', sep = ';', header = TRUE, colClasses = c('Time' = 'character', rep('double',12)))

#load Trafo coordination information
trafoLocationData <- read.csv('input/Location Trafostation.csv', sep = ';', colClasses = listColNamesLocTrafo, stringsAsFactors = FALSE, strip.white = TRUE, na.strings = c("NA",""))

#load Cell coordination information
cellLocationData <- read.csv('input/Location Anschlussobjekte.csv', sep = ';', colClasses = listColNamesLocCell, stringsAsFactors = FALSE, strip.white = TRUE, na.strings = c("NA",""))


#remove time column from sun radiation, otherwise not able to calculate the rest
timeSlots <- sunRadiationYearly$Time


#create data frames
aggrDataSetAll <- data.frame(listColNamesAggrFile)
aggrLocationData <- data.frame(c('Trafo Nr' = 'numeric', 'Anschlussobjekt' = 'character', 'C Latitude' = 'double', 'C Longitude' = 'double', 'T Leistung' = 'numeric', 'T Latitude' = 'double', 'T Longitude' = 'double')) 
cellConsYearlyTmp <- data.frame(1:1, list(c('Week_S' = 'double', 'Saturday_S' = 'double', 'Sunday_S' = 'double','Week_W' = 'double', 'Saturday_W' = 'double', 'Sunday_W' = 'double', 'Week_TP' = 'double', 'Saturday_TP' = 'double', 'Sunday_TP' = 'double')))
cellConsYearlyTmp <- 0
cellStatusData <- data.frame(c('Anschlussobjekt' = 'character', timeSlots))


#intitialisation of required files
if(!exists('packages')) source(paste(mainDir, 'files/functions.R', sep = "/", collapse = ""))


#see if the folders for the tmp production & consumption is ready
if(dir.exists(folderOutProdTmp) == FALSE) checkDir(folderOutProdTmp)
if(dir.exists(folderOutConsTmp) == FALSE) checkDir(folderOutConsTmp)

#installing all necessary packages and load them
checkPackages()

#adjusments of variables, e.g. reduction of consumption or acitvating of potential PV production
controlConsumption <- as.double(1.0)
controlProduction <- as.double(1.0)
controlActivateProvProd <- c('Good')

calculateConsumption <- TRUE
calculateProduction <- TRUE


